print("Hello, World")
print("my name is Shane.")
print("I am", 10+9, "Years old")
print("I finished high school in", 1011+1011, ", Last year in short" )
print("I love making music.")
print("I love writing music.")
print("I love playing music.")
print("I love distributing music.")
print("I play bass guitar.")
print("I play acoustic guitar.")
print("I play lead guitar.")
print("I play rhythm guitar.")
print("I play drums.")
print("I play bongo drums.")
print("I play orchestral piano.")
print("I play worship piano.")
print("I teach bass guitar.")
print("I teach acoustic guitar.")
print("I teach lead guitar.")
print("I teach rhythm guitar.")
print("I teach drums.")
print("I teach bongo drums.")
print("I teach orchestral piano.")
print("I teach worship piano.")

